<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Controle de Produção da Milã Camizetas</title>
		<link rel="stylesheet" type="text/css" href="/css/main.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/css/print.css" media="print" />
		<!--[if lte IE 6]>
			<link rel="stylesheet" type="text/css" href="/css/ie6_or_less.css" />
		<![endif]-->
		<script type="text/javascript" src="/js/common.js"></script>
	</head>
<body id="type-b">
	<div id="wrap">
	<div id="header">
		<div id="site-name">Milã Camisetas</div>
		<div id="search">
			<form action="">
				<label for="searchsite">Busca:</label>
				<input id="searchsite" name="searchsite" type="text" />
				<input type="submit" value="Vai!" class="f-submit" />
			</form>
		</div>
		<ul id="nav">
			<li class="first active">
				<a href="<?= $this->url(array('controller'=>'producao'),'default',true)?>">Produção</a>
			</li>
			<li><a href="<?= $this->url(array('controller'=>'pedidos'),'default',true)?>">Pedidos</a></li>
			<li><a href="<?= $this->url(array('controller'=>'clientes'),'default',true)?>">Clientes</a></li>
			<li><a href="<?= $this->url(array('controller'=>'eventos'),'default',true)?>">Eventos</a></li>
			<li><a href="<?= $this->url(array('controller'=>'relatorios'),'default',true)?>">Relatórios</a></li>
			<li><a href="<?= $this->url(array('controller'=>'usuarios'),'default',true)?>">Usuários</a></li>
		</ul>
	</div>
	
	<div id="content-wrap">
	
		<div id="utility">

			<ul id="nav-secondary">
				<li class="first active">
					<a href="<?= $this->url(array('controller'=>'producao'),'default',true)?>">Produção</a>
					<ul>
						<li class="first"><a href="<?= $this->url(array('controller'=>'producao', 'action' => 'design'),'default',true)?>">Design</a></li>
						<li><a href="<?= $this->url(array('controller'=>'producao', 'action' => 'fotolito'),'default',true)?>">Fotolito</a></li>
						<li><a href="<?= $this->url(array('controller'=>'producao', 'action' => 'revelacao'),'default',true)?>">Revelação</a></li>
						<li><a href="<?= $this->url(array('controller'=>'producao', 'action' => 'impressao'),'default',true)?>">Impressão</a></li>
						<li><a href="<?= $this->url(array('controller'=>'producao', 'action' => 'transferencia'),'default',true)?>">Transferência</a></li>
						<li><a href="<?= $this->url(array('controller'=>'producao', 'action' => 'cortecostura'),'default',true)?>">Corte e Costura</a></li>
						<li class="last"><a href="<?= $this->url(array('controller'=>'producao', 'action' => 'acabamentoembalagem'),'default',true)?>">Acabamento e Embalagem</a></li>
					</ul>
				</li>
			</ul>
			
		</div>
		
		<div id="content">
			<div id="breadcrumb">
				<a href="homepage.cfm">Home</a> / <a href="devtodo">Section Name</a> / <strong>Page Name</strong>
			</div>
			
			<?php echo $this->layout()->content ?>
			
			<br />
			<div id="footer">
				<p>Para obter ajuda envie um email para mila(arroba)adrianomelo.com</p>
				<p><a href="#">Contact Us</a> | <a href="#">Privacy</a> | <a href="#">Links</a></p>
			</div>
		</div>
		<div id="poweredby"><a href="http://farcry.daemon.com.au/"><img src="wsimages/mollio.gif" alt="FarCry - Mollio" /></a></div>
	</div>
	
</div>
</body>
</html>
