<h1>Resumo da Produção</h1>
<div id="producao">
	<div class="box">
		<h2 class="box-title">Próximas Entregas</h2>
		<div class="box-content">
			<ul>
				<li>25/01 - bloco giraffa</li>
				<li>27/01 - bloco kalango</li>
				<li>15/02 - aviões do forró</li>
			</ul>
		</div>
		
		<h2 class="box-title">Próximos Eventos</h2>
		<div class="box-content">
			<ul>
				<li>25/01 - bloco giraffa</li>
				<li>26/01 - bloco do camelo</li>
				<li>27/01 - bloco kalango</li>
				<li>15/02 - recife in door</li>
				<li>17/02 - olinda beer</li>
			</ul>
		</div>
	</div>
	
	<div class="box">	
		<h2 class="box-title">Fotolito</h2>
		<div class="box-content">
			<ul>
				<li><strong>10</strong> pedidos não cadastrados</li>
				<li><strong>10</strong> pedidos para imprimir</li>
			</ul>
		</div>
		
		<h2 class="box-title">Revelação</h2>
		<div class="box-content">
			<ul>
				<li><strong>10</strong> para imprimir</li>
			</ul>
		</div>
		
		<h2 class="box-title">Impressão</h2>
		<div class="box-content">
			<ul>
				<li><strong>10</strong> para imprimir</li>
			</ul>
		</div>
		
		<h2 class="box-title">Transferência</h2>
		<div class="box-content">
			<ul>
				<li><strong>10</strong> para imprimir</li>
			</ul>
		</div>
		
		<h2 class="box-title">Corte e Costura</h2>
		<div class="box-content">
			<ul>
				<li><strong>10</strong> para imprimir</li>
			</ul>
		</div>
		
		<h2 class="box-title">Acabamento e Embalagem</h2>
		<div class="box-content">
			<ul>
				<li><strong>10</strong> para imprimir</li>
			</ul>
		</div>
	</div>
	
	<div class="box">
		<h2 class="box-title">Últimos Layouts Produzidos</h2>
		<div class="box-content">
			<ul>
				<li>25/01 - bloco giraffa</li>
				<li>27/01 - bloco kalango</li>
				<li>15/02 - aviões do forró</li>
			</ul>
		</div>
		
		<h2 class="box-title">Pedidos</h2>
		<div class="box-content">
			<ul>
				<li><strong>10</strong> em produção</li>
				<li><strong>10</strong> em negociação</li>
				<li><strong>200</strong> finalizados</li>
			</ul>
		</div>
	</div>
</div>
